"""Added workers tables

Revision ID: 511eddd1f4e2
Revises: 033f70571cc3
Create Date: 2023-08-24 17:03:07.390599

"""
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision = "511eddd1f4e2"
down_revision = "033f70571cc3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=90), nullable=False),
        sa.Column("code", sa.String(length=45), nullable=False),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("email", sa.String(length=90), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=True,
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_workers_id"), "workers", ["id"], unique=False)
    op.alter_column("users", "username", existing_type=mysql.VARCHAR(length=45), nullable=False)
    op.alter_column("users", "hashed_password", existing_type=mysql.VARCHAR(length=255), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "hashed_password", existing_type=mysql.VARCHAR(length=255), nullable=True)
    op.alter_column("users", "username", existing_type=mysql.VARCHAR(length=45), nullable=True)
    op.drop_index(op.f("ix_workers_id"), table_name="workers")
    op.drop_table("workers")
    # ### end Alembic commands ###
